# 🎬 Movie Recommendation System using Content-Based Filtering

## 📌 Problem Statement
In modern digital entertainment platforms, users are presented with thousands of movies to choose from. This large volume of content often makes it difficult for users to quickly find movies that match their preferences. Manually browsing through extensive catalogs can be inefficient and time-consuming.  

To address this challenge, recommendation systems are widely used to automatically suggest relevant content to users. A **content-based recommendation system** analyzes the characteristics of items—such as movie genres—and identifies similarities between them. By doing so, it can recommend movies that are closely related to a movie the user already likes.

---

## 🎯 Objective
The objective of this project is to build a **content-based movie recommendation system** that suggests similar movies based on their genre information.

The system performs the following tasks:

- Convert textual movie genre data into numerical feature vectors using **TF-IDF (Term Frequency–Inverse Document Frequency)**.
- Measure similarity between movies using **Cosine Similarity**.
- Recommend the **top 5 most similar movies** based on the selected movie.
- Display recommendations along with their **similarity scores**.
- Develop an **interactive graphical user interface (GUI)** using **Streamlit**, allowing users to enter a movie title and instantly receive personalized recommendations.

This project demonstrates how machine learning techniques can be applied to create an intelligent and interactive recommendation system that improves the user’s content discovery experience.

# Step 1: Import Required Libraries

In [1]:
# Import pandas for handling dataset
import pandas as pd

# Convert text data (genres) into numeric vectors
from sklearn.feature_extraction.text import TfidfVectorizer

# Measure similarity between movies
from sklearn.metrics.pairwise import cosine_similarity
print("✅ Libraries Imported Successfully")
# -------------------------------
# Ignore Warnings
# -------------------------------
import warnings

# Ignore all warnings
warnings.filterwarnings('ignore')

print("✅ All warnings will be suppressed")

✅ Libraries Imported Successfully
✅ All warnings will be suppressed

# Step 2: Load the Movie Dataset

In [4]:
# Load dataset
movies = pd.read_csv("movies.csv")

# Display first 5 rows
print("Dataset shape:", movies.shape)
movies.head()

Dataset shape: (10329, 3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

# Step 3: Check Missing Values

In [5]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

# Step 4: Feature Engineering – Convert Genres to TF-IDF Vectors

In [6]:
# Create TF-IDF object
tfidf = TfidfVectorizer(stop_words='english')

# Transform genres column
tfidf_matrix = tfidf.fit_transform(movies['genres'])

# Check matrix shape
print(tfidf_matrix.shape)

(10329, 23)

# Step 5: Compute Cosine Similarity Matrix

In [7]:
# Calculate cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Print shape
print(cosine_sim.shape)

(10329, 10329)

# Step 6: Create Movie Title to Index Mapping

In [8]:
# Create title index mapping
indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

# Display first few
indices.head()

title
Toy Story (1995)                      0
Jumanji (1995)                        1
Grumpier Old Men (1995)               2
Waiting to Exhale (1995)              3
Father of the Bride Part II (1995)    4
dtype: int64

# Step 7: Build the Movie Recommendation Function

In [14]:
def recommend_movies(title, cosine_sim=cosine_sim):

    # Get movie index
    idx = indices[title]

    # Get similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort movies based on similarity
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Select top 5 similar movies (excluding itself)
    sim_scores = sim_scores[1:6]

    # Extract movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Get movie titles
    recommendations = movies.iloc[movie_indices][['title']]

    # Add similarity scores
    recommendations['Similarity Score'] = [i[1] for i in sim_scores]

    return recommendations

# Step 8: Test the Recommendation System

In [13]:
recommend_movies("Toy Story (1995)")

                                               title  Similarity Score
1815                                     Antz (1998)               1.0
2496                              Toy Story 2 (1999)               1.0
2967  Adventures of Rocky and Bullwinkle, The (2000)               1.0
3166                Emperor's New Groove, The (2000)               1.0
3811                           Monsters, Inc. (2001)               1.0

In [11]:
recommend_movies("Jumanji (1995)")

                                          title  Similarity Score
55           Indian in the Cupboard, The (1995)               1.0
112           NeverEnding Story III, The (1994)               1.0
817             Escape to Witch Mountain (1975)               1.0
1604  Darby O'Gill and the Little People (1959)               1.0
1652                        Return to Oz (1985)               1.0

# Step 9: Save the Model for Deployment

In [12]:
import joblib

joblib.dump(cosine_sim, "similarity_model.pkl")
joblib.dump(indices, "movie_indices.pkl")

['movie_indices.pkl']

# Conclusion

In this project, a **content-based movie recommendation system** was developed to suggest movies that are similar based on their genre features. The system uses **TF-IDF (Term Frequency–Inverse Document Frequency)** to convert textual genre information into numerical feature vectors, allowing the model to understand and process the data effectively.

To measure the similarity between movies, **cosine similarity** was applied to the TF-IDF feature matrix. This approach enables the system to identify movies with similar genre characteristics and recommend the **top 5 most relevant movies** along with their similarity scores.

Additionally, an **interactive Streamlit graphical user interface (GUI)** was implemented, allowing users to enter a movie title and instantly receive recommendations. This improves usability and demonstrates how machine learning models can be integrated into simple web applications.

Overall, this project highlights how **content-based filtering techniques** can be used to build practical recommendation systems that help users discover relevant content efficiently. The approach can be further improved by incorporating additional features such as movie descriptions, user ratings, or hybrid recommendation techniques.